export const LOGIN_USER = 'LOGIN_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_LIST_CATEGORIES = 'GET_LIST_CATEGORIES';
export const GET_LIST_CATEGORIES_DONE = 'GET_LIST_CATEGORIES_DONE';

export const ADD_CART = 'ADD_CART_';
export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS';

export const EDIT_CART = 'EDIT_CART';
export const EDIT_CART_SUCCESS = 'EDIT_CART_SUCCESS';

export const DELETE_CART = 'DELETE_CART';
export const DELETE_CART_SUCCESS = 'DELETE_CART_SUCCESS';

export const SET_LOADING = 'SET_GLOBAL_LOADING';
